services:
  - type: web
    name: expense-tracker-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SQL_SERVER
        sync: false
      - key: SQL_DATABASE
        sync: false
      - key: SQL_USERNAME
        sync: false
      - key: SQL_PASSWORD
        sync: false
      - key: SQL_TRUSTED_CONNECTION
        value: "no"
      - key: SQL_DRIVER
        value: "ODBC Driver 18 for SQL Server"
